version: 0.2
phases:
  install:
    commands:
      - npm install

  build:
    commands:
      - npm test

  post_build:
    commands:
      - npm run build
      - aws s3 sync ./dist s3://unlucky-guy --grants full=uri=http://acs.amazonaws.com/groups/global/AllUsers
